# Generated by Django 5.0.14 on 2026-07-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, help_text='English category name (optional). Falls back to Vietnamese name.', max_length=100),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='description_en',
            field=models.TextField(blank=True, help_text='English description (optional). Falls back to Vietnamese description.'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name_en',
            field=models.CharField(blank=True, help_text='English name (optional). Falls back to Vietnamese name.', max_length=200),
        ),
        migrations.AddField(
            model_name='newsfeed',
            name='content_en',
            field=models.TextField(blank=True, help_text='English content (optional). Falls back to Vietnamese content.'),
        ),
        migrations.AddField(
            model_name='newsfeed',
            name='title_en',
            field=models.CharField(blank=True, help_text='English title (optional). Falls back to Vietnamese title.', max_length=200),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(help_text='Vietnamese description'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(help_text='Vietnamese name', max_length=200),
        ),
        migrations.AlterField(
            model_name='newsfeed',
            name='content',
            field=models.TextField(help_text='Vietnamese content'),
        ),
        migrations.AlterField(
            model_name='newsfeed',
            name='title',
            field=models.CharField(help_text='Vietnamese title', max_length=200),
        ),
    ]
