# Generated by Django 5.0.14 on 2026-07-02 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsfeed',
            options={'ordering': ['-created_at'], 'verbose_name': 'News Feed', 'verbose_name_plural': 'News Feeds'},
        ),
    ]
