# Generated by Django 5.0.14 on 2026-07-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fulfillment_type',
            field=models.CharField(choices=[('pickup', 'Tự đến lấy'), ('delivery', 'Giao hàng')], default='delivery', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash_on_delivery', 'Thanh toán khi nhận hàng'), ('online_payment', 'Thanh toán online')], default='cash_on_delivery', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, help_text='Required for delivery orders, leave blank for pickup'),
        ),
    ]
